---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  dagger:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/dagger/modules.yaml

dotenv: ['.env', '{{.HOME}}/.env']

tasks:
  test-all:
    desc: Run all tests
    deps: ['git:check']
    cmds:
      - task: test-crossplane-configuration
      - task: test-vmtemplate
      - task: test-vm
      - task: test-go-microservice
      - task: test-repository-linting
      - task: test-crossplane-configuration
      - task: test-presentation-init
      - task: test-presentation-add-content

  test-crossplane-configuration:
    desc: Test crossplane-configuration module
    cmds:
      - |
        mkdir -p /tmp/apps || true
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --name openebs \
        --defaults-file {{ .DEFAULTS_FILE }} \
        --variables-file {{ .VARIABLES_FILE }} \
        --variables='{{ .VARIABLES }}' \
        --progress plain -vv \
        export --path={{ .EXPORT_PATH }}
      - |
        echo "✓ Configuration generated successfully"
        echo "Output location: {{ .EXPORT_PATH }}"
      - |
        echo ""
        echo "Generated files:"
        if command -v tree &> /dev/null; then
          tree {{ .EXPORT_PATH }}
        else
          find {{ .EXPORT_PATH }} -type f | sort
        fi
    vars:
      MODULE: crossplane-configuration
      FUNCTION: create
      DEFAULTS_FILE: ./tests/crossplane-configuration/defaults.yaml
      VARIABLES_FILE: ./tests/crossplane-configuration/openebs-variables.yaml
      VARIABLES: 'crossplaneVersion=4.13.0,functions=[{"Name":"function-patch-and-transform","ApiVersion":"pt.fn.crossplane.io/v1beta1","PackageURL":"xpkg.upbound.io/function-patch-and-transform","Version":"v0.1.0"},{"Name":"function-go-templating","ApiVersion":"gotemplating.fn.crossplane.io/v1beta1","PackageURL":"xpkg.upbound.io/function-go-templating","Version":"v0.1.0"}]'
      EXPORT_PATH: /tmp/apps/openebs

  test-repository-linting:
    desc: Test repository-linting module
    cmds:
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --src {{ .CODE_TEST_DIR }} \
        export --path={{ .EXPORT_PATH }}
    vars:
      MODULE: repository-linting
      FUNCTION: validate-multiple-technologies
      CODE_TEST_DIR: tests/repository-linting/test-repo
      EXPORT_PATH: /tmp/all-findings.txt

  test-go-microservice:
    desc: Test go-microservice module
    cmds:
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --src {{ .CODE_TEST_DIR }} \
        --lintCanFail=true \
        --progress plain -vv \
        export --path=/tmp/report.json
    vars:
      MODULE: go-microservice
      FUNCTION: run-static-stage
      CODE_TEST_DIR: tests/{{ .MODULE }}/calculator

  test-vmtemplate:
    desc: Test vmtemplate module
    cmds:
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --packer-config-dir {{ .CODE_TEST_DIR }} \
        --packer-config {{ .TEST_CONFIG }} \
        --packer-version {{ .PACKER_VERSION }} \
        --progress plain -vv
    vars:
      MODULE: vmtemplate
      FUNCTION: bake
      CODE_TEST_DIR: tests/{{ .MODULE }}/hello
      TEST_CONFIG: hello.pkr.hcl
      PACKER_VERSION: 1.13.1

  test-vm:
    desc: Test vm module
    cmds:
      - |
        echo "Running bake command for vm module - apply terraform code"
        rm -rf {{ .EXPORTED_TF_WORKSPACE }} || true
      - |
        mkdir -p {{ .EXPORTED_TF_WORKSPACE }} || true
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --terraform-dir {{ .TF_CODE_TEST_DIR }} \
        --encrypted-file {{ .SOPS_ENCRYPTED_VARS }} \
        --operation apply \
        --sops-key={{ .SOPS_KEY }} \
        -vv --progress plain \
        export --path={{ .EXPORTED_TF_WORKSPACE }}
      - |
        echo "Running bake command for vm module - apply terraform code over existing workspace"
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --terraform-dir {{ .EXPORTED_TF_WORKSPACE }} \
        --encrypted-file {{ .SOPS_ENCRYPTED_VARS }} \
        --operation apply \
        --sops-key={{ .SOPS_KEY }} \
        -vv --progress plain \
        export --path={{ .EXPORTED_TF_WORKSPACE }}
    vars:
      MODULE: vm
      FUNCTION: bake-local
      TF_CODE_TEST_DIR: tests/{{ .MODULE }}/tf
      SOPS_ENCRYPTED_VARS: tests/{{ .MODULE }}/terraform.tfvars.enc.json
      EXPORTED_TF_WORKSPACE: /tmp/terraform/vms/dagger/
      SOPS_KEY: env:SOPS_AGE_KEY

  install-module:
    desc: Install a Dagger module into an existing module
    cmds:
      - cd {{ .EXISTING_MODULE }} && dagger install {{ .MODULE_TO_INSTALL }}
    vars:
      EXISTING_MODULE:
        sh: |
          gum choose $(ls -d */ \
            | grep -vE '(^tests/|^vm/|^vmtemplate/)' \
            | sed 's:/$::')
      MODULE_TO_INSTALL:
        sh: |
          gum input \
            --placeholder "Module to install (default: github.com/stuttgart-things/dagger/<MODULE>@v0.37.0)" \
            --value "github.com/stuttgart-things/dagger/<MODULE>@v0.36.0"

  release:
    desc: release new version
    deps:
      - test-all
    cmds:
      - task: git:pr
      - npx semantic-release --dry-run
      - npx semantic-release --debug --no-ci
      - echo released version $(git describe --tags --abbrev=0)

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  test-presentation-init:
    desc: Test presentation init module
    cmds:
      - |
        echo "Running init command for presentation module"
        rm -rf {{ .EXPORT_PATH }} || true
      - |
        mkdir -p {{ .EXPORT_PATH }} || true
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --name {{ .PRESENTATION_NAME }} \
        --progress plain -vv \
        export --path={{ .EXPORT_PATH }}
      - |
        echo "✓ Presentation initialized successfully"
        echo "Output location: {{ .EXPORT_PATH }}"
      - |
        echo ""
        echo "Generated files:"
        if command -v tree &> /dev/null; then
          tree {{ .EXPORT_PATH }}
        else
          find {{ .EXPORT_PATH }} -type f | sort
        fi
    vars:
      MODULE: presentations
      FUNCTION: init
      PRESENTATION_NAME: test-presentation
      EXPORT_PATH: /tmp/presentations/{{ .PRESENTATION_NAME }}

  test-presentation-add-content:
    desc: Test presentation add-content module
    cmds:
      - |
        echo "Running add-content command for presentation module"
        rm -rf {{ .EXPORT_PATH }} || true
      - |
        mkdir -p {{ .EXPORT_PATH }} || true
      - |
        dagger call -m {{ .MODULE }} {{ .FUNCTION }} \
        --src {{ .SOURCE_DIR }} \
        --presentation-file {{ .CONFIG_FILE }} \
        --progress plain -vv \
        export --path={{ .EXPORT_PATH }}
      - |
        echo "✓ Content added successfully"
        echo "Output location: {{ .EXPORT_PATH }}"
      - |
        echo ""
        echo "Generated slide files:"
        if command -v tree &> /dev/null; then
          tree {{ .EXPORT_PATH }}
        else
          find {{ .EXPORT_PATH }} -type f -name "*.md" | sort
        fi
    vars:
      MODULE: presentations
      FUNCTION: add-content
      SOURCE_DIR: tests/presentations
      CONFIG_FILE: tests/presentations/presentation.yaml
      EXPORT_PATH: /tmp/presentations/slides
