package main

import "testing"

func TestExtractTemplateName(t *testing.T) {
	log := `==> Wait completed after 22 minutes 24 seconds
2025/07/04 10:21:05 machine readable: vsphere-iso.autogenerated_1,artifact []string{"0", "id", "ubuntu24-20250704"}
2025/07/04 10:21:05 machine readable: vsphere-iso.autogenerated_1,artifact []string{"0", "string", "ubuntu24-20250704"}`

	expected := "ubuntu24-20250704"
	result := ExtractTemplateName(log)

	if result != expected {
		t.Errorf("expected %q, got %q", expected, result)
	}
}
